"use client";

import { useAuth } from "@/components/auth/AuthProvider";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Sparkles, MessageSquare, Star, Megaphone, Image as ImageIcon, Video, Camera, TrendingUp } from "lucide-react";
import Link from "next/link";
import { useEffect, useState } from "react";
import { getDashboardInsights } from "@/services/insights.service";
import { Insight } from "@/types/insights";
import { AIInsights } from "@/components/ai/AIInsights";

export default function DashboardPage() {
  const { user } = useAuth();
  const [insights, setInsights] = useState<Insight[]>([]);

  useEffect(() => {
    const fetchInsights = async () => {
      try {
        const res = await getDashboardInsights();
        setInsights(res.data as unknown as Insight[]);
      } catch (err) {
        console.error("Failed to load insights", err);
      }
    };
    fetchInsights();
  }, []);

  return (
    <div className="space-y-8 animate-in fade-in duration-500">
      <div>
        <h1 className="text-3xl font-bold tracking-tight text-white">
          Good Morning, {user?.name || "Sharma Fashion"} <span className="inline-block animate-wave">👋</span>
        </h1>
        <p className="text-text-muted mt-2">Here is your AI marketing summary for today.</p>
      </div>

      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
        <Card className="bg-brand-purple/10 border-brand-purple/20">
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium text-white">Today&apos;s Post</CardTitle>
            <ImageIcon className="h-4 w-4 text-brand-purple" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-brand-purple">Ready</div>
            <p className="text-xs text-brand-purple/70 mt-1">Generated by AI at 8:00 AM</p>
          </CardContent>
        </Card>
        
        <Card className="bg-brand-pink/10 border-brand-pink/20">
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium text-white">Today&apos;s Reel</CardTitle>
            <Video className="h-4 w-4 text-brand-pink" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-brand-pink">Ready</div>
            <p className="text-xs text-brand-pink/70 mt-1">Script & voiceover generated</p>
          </CardContent>
        </Card>

        <Link href="/messages" className="block">
          <Card className="h-full bg-surface hover:border-brand-purple/50 transition-colors">
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium text-white">Customer Messages</CardTitle>
              <MessageSquare className="h-4 w-4 text-text-muted" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold text-white">3</div>
              <p className="text-xs text-brand-coral mt-1">2 require your attention</p>
            </CardContent>
          </Card>
        </Link>

        <Link href="/reviews" className="block">
          <Card className="h-full bg-surface hover:border-brand-pink/50 transition-colors">
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium text-white">Google Reviews</CardTitle>
              <Star className="h-4 w-4 text-brand-coral" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold text-white">2</div>
              <p className="text-xs text-brand-purple mt-1">AI replies drafted</p>
            </CardContent>
          </Card>
        </Link>
      </div>

      <div className="space-y-4">
        <h2 className="text-xl font-semibold tracking-tight text-white">Quick Actions</h2>
        <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
          <Button variant="outline" className="h-24 flex flex-col gap-2 relative overflow-hidden group hover:border-brand-purple hover:bg-brand-purple/10" asChild>
            <Link href="/content?type=post">
              <ImageIcon className="h-6 w-6 text-brand-purple" />
              <span className="font-semibold text-white">Create Post</span>
              <div className="absolute inset-0 bg-gradient-to-r from-transparent via-white/10 to-transparent -translate-x-full group-hover:animate-shimmer" />
            </Link>
          </Button>
          
          <Button variant="outline" className="h-24 flex flex-col gap-2 relative overflow-hidden group hover:border-brand-pink hover:bg-brand-pink/10" asChild>
            <Link href="/create/reel">
              <Video className="h-6 w-6 text-brand-pink" />
              <span className="font-semibold text-white">Create Reel</span>
              <div className="absolute inset-0 bg-gradient-to-r from-transparent via-white/10 to-transparent -translate-x-full group-hover:animate-shimmer" />
            </Link>
          </Button>

          <Button variant="outline" className="h-24 flex flex-col gap-2 relative overflow-hidden group hover:border-brand-coral hover:bg-brand-coral/10" asChild>
            <Link href="/ai-photoshoot">
              <Camera className="h-6 w-6 text-brand-coral" />
              <span className="font-semibold text-white">AI Photoshoot</span>
              <div className="absolute inset-0 bg-gradient-to-r from-transparent via-white/10 to-transparent -translate-x-full group-hover:animate-shimmer" />
            </Link>
          </Button>

          <Button variant="outline" className="h-24 flex flex-col gap-2 relative overflow-hidden group hover:border-white/50 hover:bg-white/5" asChild>
            <Link href="/create-ad">
              <Megaphone className="h-6 w-6 text-white" />
              <span className="font-semibold text-white">Create Ad</span>
              <div className="absolute inset-0 bg-gradient-to-r from-transparent via-white/10 to-transparent -translate-x-full group-hover:animate-shimmer" />
            </Link>
          </Button>
        </div>
      </div>

      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-7">
        <Card className="col-span-4 bg-surface border-border">
          <CardHeader>
            <CardTitle className="text-white">Recent Campaigns</CardTitle>
            <CardDescription className="text-text-muted">
              Your active marketing campaigns performance this week.
            </CardDescription>
          </CardHeader>
          <CardContent className="flex flex-col items-center justify-center h-[300px] text-text-muted bg-surface-secondary rounded-lg mx-6 mb-6 border border-dashed border-border">
            <Sparkles className="h-10 w-10 text-text-muted mb-4" />
            <p>No active campaigns right now.</p>
            <Button variant="link" className="text-brand-pink mt-2">Start a campaign</Button>
          </CardContent>
        </Card>
        
        <Card className="col-span-3 bg-surface border-border">
          <CardHeader>
            <CardTitle className="text-white">AI Insights</CardTitle>
            <CardDescription className="text-text-muted">
              Recommendations based on your audience.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <AIInsights insights={insights} />
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
