"use client";

import { useAuth } from "@/components/auth/AuthProvider";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Sparkles, MessageSquare, Star, Megaphone, Image as ImageIcon, Video, Camera, TrendingUp } from "lucide-react";
import Link from "next/link";
import { useEffect, useState } from "react";
import { getDashboardInsights } from "@/services/insights.service";
import { Insight } from "@/types/insights";
import { AIInsights } from "@/components/ai/AIInsights";

export default function DashboardPage() {
  const { user } = useAuth();
  const [insights, setInsights] = useState<Insight[]>([]);

  useEffect(() => {
    const fetchInsights = async () => {
      try {
        const res = await getDashboardInsights();
        setInsights(res.data);
      } catch (err) {
        console.error("Failed to load insights", err);
      }
    };
    fetchInsights();
  }, []);

  return (
    <div className="space-y-8 animate-in fade-in duration-500">
      <div>
        <h1 className="text-3xl font-bold tracking-tight text-foreground">
          Good Morning, {user?.name || "Sharma Fashion"} <span className="inline-block animate-wave">👋</span>
        </h1>
        <p className="text-muted-foreground mt-2">Here is your AI marketing summary for today.</p>
      </div>

      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
        <Card className="bg-gradient-to-br from-primary-50 to-background border-primary-100">
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Today&apos;s Post</CardTitle>
            <ImageIcon className="h-4 w-4 text-primary-600" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-primary-700">Ready</div>
            <p className="text-xs text-muted-foreground mt-1">Generated by AI at 8:00 AM</p>
          </CardContent>
        </Card>
        
        <Card className="bg-gradient-to-br from-indigo-50 to-background border-indigo-100">
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Today&apos;s Reel</CardTitle>
            <Video className="h-4 w-4 text-indigo-600" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-indigo-700">Ready</div>
            <p className="text-xs text-muted-foreground mt-1">Script & voiceover generated</p>
          </CardContent>
        </Card>

        <Link href="/messages" className="block">
          <Card className="h-full hover:border-primary-500/50 transition-colors">
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">Customer Messages</CardTitle>
              <MessageSquare className="h-4 w-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">3</div>
              <p className="text-xs text-muted-foreground mt-1">2 require your attention</p>
            </CardContent>
          </Card>
        </Link>

        <Link href="/reviews" className="block">
          <Card className="h-full hover:border-amber-500/50 transition-colors">
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">Google Reviews</CardTitle>
              <Star className="h-4 w-4 text-amber-500" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">2</div>
              <p className="text-xs text-muted-foreground mt-1">AI replies drafted</p>
            </CardContent>
          </Card>
        </Link>
      </div>

      <div className="space-y-4">
        <h2 className="text-xl font-semibold tracking-tight">Quick Actions</h2>
        <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
          <Button variant="outline" className="h-24 flex flex-col gap-2 relative overflow-hidden group border-primary-200 hover:border-primary-500 hover:bg-primary-50" asChild>
            <Link href="/content?type=post">
              <ImageIcon className="h-6 w-6 text-primary-600" />
              <span className="font-semibold text-primary-900">Create Post</span>
              <div className="absolute inset-0 bg-gradient-to-r from-transparent via-white/50 to-transparent -translate-x-full group-hover:animate-shimmer" />
            </Link>
          </Button>
          
          <Button variant="outline" className="h-24 flex flex-col gap-2 relative overflow-hidden group hover:border-indigo-500 hover:bg-indigo-50" asChild>
            <Link href="/create/reel">
              <Video className="h-6 w-6 text-indigo-600" />
              <span className="font-semibold text-indigo-900">Create Reel</span>
              <div className="absolute inset-0 bg-gradient-to-r from-transparent via-white/50 to-transparent -translate-x-full group-hover:animate-shimmer" />
            </Link>
          </Button>

          <Button variant="outline" className="h-24 flex flex-col gap-2 relative overflow-hidden group hover:border-amber-500 hover:bg-amber-50" asChild>
            <Link href="/ai-photoshoot">
              <Camera className="h-6 w-6 text-amber-600" />
              <span className="font-semibold text-amber-900">AI Photoshoot</span>
              <div className="absolute inset-0 bg-gradient-to-r from-transparent via-white/50 to-transparent -translate-x-full group-hover:animate-shimmer" />
            </Link>
          </Button>

          <Button variant="outline" className="h-24 flex flex-col gap-2 relative overflow-hidden group hover:border-emerald-500 hover:bg-emerald-50" asChild>
            <Link href="/create-ad">
              <Megaphone className="h-6 w-6 text-emerald-600" />
              <span className="font-semibold text-emerald-900">Create Ad</span>
              <div className="absolute inset-0 bg-gradient-to-r from-transparent via-white/50 to-transparent -translate-x-full group-hover:animate-shimmer" />
            </Link>
          </Button>
        </div>
      </div>

      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-7">
        <Card className="col-span-4">
          <CardHeader>
            <CardTitle>Recent Campaigns</CardTitle>
            <CardDescription>
              Your active marketing campaigns performance this week.
            </CardDescription>
          </CardHeader>
          <CardContent className="flex flex-col items-center justify-center h-[300px] text-muted-foreground bg-muted/20 rounded-lg mx-6 mb-6 border border-dashed border-border">
            <Sparkles className="h-10 w-10 text-muted-foreground/40 mb-4" />
            <p>No active campaigns right now.</p>
            <Button variant="link" className="text-primary-600 mt-2">Start a campaign</Button>
          </CardContent>
        </Card>
        
        <Card className="col-span-3">
          <CardHeader>
            <CardTitle>AI Insights</CardTitle>
            <CardDescription>
              Recommendations based on your audience.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <AIInsights insights={insights} />
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
